### ISSUE TITLE
Next & Previous Month Disabled After Polymer Build

### ISSUE THREAD

**Issue by ZachMoreno** [edwardsharp/sched-datepicker#5]
I have, what feels like, a strange question for you. Before I build/deploy the Next & Previous buttons work are enabled & work as intended, after I build they're disabled. Here's a [short video](https://youtu.be/oxTP67iUp1E) to help illustrate. I'd like them to remain enabled & any help you can provide would be great. Thank You!

**Comment by edwardsharp** [comment]
@ZachMoreno 👋 i can't really give much feedback with a video... if you provide code then i might be able to help.

**Comment by ZachMoreno** [comment]
My b, I followed your minimal example

```
<sched-datepicker date="{{ date }}" is-selected="{{ isSelected }}">
</sched-datepicker>
```

**Comment by edwardsharp** [comment]
hmm, you're leaving out a lot of details which i don't understand and also goes against the spirit of the GPL-3.0 license of sched-datepicker. 

if you don't want to publish the source for your app, that's chill, in which case i'd suggest not using GPL-3.0 code.
